### ISSUE TITLE
upgrade: kiam-server|agent: agent goes into crashloopbackoff

### ISSUE THREAD

**Issue by tasdikrahman** [uswitch/kiam#128] opened 2018-07-30 10:41 UTC
Greetings, 

I was upgrading the kiam-server|agent versions, going from 2.4 -> 2.7 sequentially. But when I tried the same from 2.7 -> 2.8. 

The agent pod, when coming up would throw

```
$ kubectl logs kiam-agent-wrhb5 -n kube-system -f  {"level":"info","msg":"configuring iptables","time":"2018-07-30T10:33:17Z"}
{"level":"info","msg":"started prometheus metric listener 0.0.0.0:9620","time":"2018-07-30T10:33:17Z"}
{"level":"fatal","msg":"error creating server gateway: error waiting for address being available in the balancer: context deadline exceeded","time":"2018-07-30T10:33:17Z"}
```

tried deleting the pod and letting it come up again, but would go into crashloopbackoff again. 

Let me know if you want any other details/logs.

**Comment by pingles** [comment] 2018-07-30 10:57
Please stick to v2.7 for now. We're working on fixes that'll be released as 3.0.

**Comment by pingles** [comment] 2018-07-30 10:57
I'll label this as a bug and keep it open until we release 3.0. Thanks for reporting and documenting.

**Comment by tasdikrahman** [comment] 2018-07-30 11:51
Hey @pingles , thanks for the quick response. :)

Just curious if you have an open issue/PR for the same, if you don't mind me prying.

**Comment by pingles** [comment] 2018-07-30 12:18
For this issue? Or you mean an issue/PR for 3.0?

We've got a milestone (https://github.com/uswitch/kiam/milestone/1) with the open issues that are left to close ahead of the release- some of which are in progress/close to finished. I've been on holiday for a week so just catching up with things now.

**Comment by pingles** [comment] 2018-08-03 08:48
I'm going to close this as its a duplicate of #94. First RC should be soon.

**Closed by pingles** 2018-08-03 08:48 UTC
Labels: bug
