### ISSUE TITLE
Prefetching credentials logs errors for roles for which sts:AssumeRole is not given

### ISSUE THREAD

**Issue by ankon** [uswitch/kiam#7] opened 2017-06-02 13:43 UTC
This is more of a discussion issue than an actual bug (from my understanding).

What I have is a cluster with a couple of worker nodes, each of which has the "worker" role. Additionally there is a controlplane node which only runs the api server and some very few critical pods from the kube-system namespace. This node has the "controlplane" role. This is what https://github.com/kubernetes-incubator/kube-aws produces in a nutshell.

A kiam pod is put on all these nodes, which seems reasonable: it's in the kube-system NS, and it should also provide credentials for those systems pods if needed -- especially when we end up with a default role (see #1).

With all that what I see is a lot of errors in the kiam pod on the controlplane node, caused by missing permissions for the controlplane role to assume roles of pods that are supposed to only run on the worker nodes. 

I'm wondering what the "story" here should be:
1. Document the behavior somehow, and essentially ignore the errors -- after all these pods will never appear, and therefore the failures in prefetching are irrelevant
2. Somehow avoid querying these roles
3. Silence the errors in some way?

**Comment by pingles** [comment] 2017-06-02 13:50
Ah interesting- so this is the cause of #5 that you reported?

It's definitely worth doing 1- I hadn't even considered that we'd attempt to assume roles that the node would be denied from. 

I think 3 is probably not great- at least in its current form we'd still like to see errors reported if its unable to retrieve credentials for a role. 

Which leaves us with 2- perhaps using some kind of Node annotation to whitelist/blacklist roles? That feels like the better solution but is perhaps getting a little close to just mirroring AWS policy and might get confusing when one is slightly out of sync with the other.

Will have to ponder on it.

**Comment by ankon** [comment] 2017-06-02 13:58
> Ah interesting- so this is the cause of #5 that you reported?

I don't think so - #5 appeared after I just gave the proper trust relationships so that the controlplane role could do the needed calls (basically removing some noise from the logs so I could see what else gets stuck). I've seen #5 on both "worker" and "controlplane" nodes, so there must be something more going on there.

**Comment by pingles** [comment] 2017-06-06 08:43
Ok so I think if we change the way kiam works we can address this and improve a few other pieces.

I think if we change kiam to work in two parts: an agent that runs on each node (responsible for the iptables proxy intercept), and a server piece that can be operated as a regular deployment/service.

I guess there are a few advantages:

1. The server component (responsible for tracking pods, requesting credentials etc.) can be placed on a node with the permission to call `AssumeRole`.
2. The server can be updated using a regular rolling deployment.
3. It means that the number of AWS calls grows in a more controlled way- rather than growing proportional to cluster size it would be dependent on the number of server pods running.

Let me know if you think this would help address the issue- if so I'll close this issue and create one to cover the change.

**Comment by ankon** [comment] 2017-06-19 10:50
I think that would indeed be reasonable to do!

**Comment by pingles** [comment] 2017-10-21 12:09
@ankon it's been a while since you were using Kiam (not sure if you still are?). We've been working on separating it into an agent (run on each node to intercept metadata requests) and server (manages pods and credentials). It's in master and a 2.0-rc2 image is on Quay.io. We'll mark it as a finished release in a few days once we've observed it in a cluster that gets heavier load.

**Comment by pingles** [comment] 2017-10-25 14:22
Just to update here- I've tagged v2.0 and the image is available on quay.io. I'm going to close this for now- the v2.0 release includes separated agents and servers so that credentials can be retrieved only by a subset of nodes.

**Closed by pingles** 2017-10-25 14:22 UTC
Labels: enhancement
