### ISSUE TITLE
failed to load system roots and no roots provided - TLS error

### ISSUE THREAD

**Issue by cdenneen** [uswitch/kiam#36] opened 2018-02-14 18:05 UTC
```
{"generation.metadata":0,"level":"error","msg":"error warming credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided","pod.iam.role":"arn:aws:iam::###########:role/chrisiamtest1","pod.name":"aws-cli3","pod.namespace":"default","pod.status.ip":"100.112.74.130","pod.status.phase":"Running","resource.version":"4849725","time":"2018-02-14T17:59:54Z"}

{"generation.metadata":0,"level":"error","msg":"error warming credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided","pod.iam.role":"chrisiamtest1","pod.name":"aws-cli","pod.namespace":"default","pod.status.ip":"100.112.74.129","pod.status.phase":"Running","resource.version":"4849455","time":"2018-02-14T17:59:54Z"}

{"level":"error","msg":"error requesting credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided","pod.iam.role":"arn:aws:iam::############:role/chrisiamtest1","time":"2018-02-14T18:00:54Z"}
```

I've tried with just using the role name and the full ARN in the pod deployment.
Can someone help me understand what this error means?
Is there documentation on how to specify the base-arn or is autodetect the best solution?

**Comment by cdenneen** [comment] 2018-02-14 18:22
I've logged into agent/server and the TLS secrets are in `/etc/kiam/tls` is they are supposed to be: https://github.com/uswitch/kiam/blob/master/docs/TLS.md

**Comment by pingles** [comment] 2018-02-16 11:51
@cdenneen The published docker image doesn't have any trusted CAs included so it's failing to interact with the AWS APIs. The container expects these to be in `/etc/ssl/certs`.

We use CoreOS Container Linux and so mount the CAs from the host into the container (so updates to the host propagate to the containers).

The relevant bits in the deployment manifests are:

* https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L21
* https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L44

Hope that helps. I'm going to close this for now but if something else happens please comment and we'll try to help.

**Closed by pingles** 2018-02-16 11:51 UTC

**Comment by cdenneen** [comment] 2018-02-16 14:47
@pingles Thanks for sending me down the correct path. (the kops hosts have a `/usr/share/ca-certificates` with a bunch of mozilla certificates but it doesn't seem to be what is needed here so update is necessary. Maybe include ca-certificates in the docker image to avoid different underlying hosts having ca-certificates in the wrong places or create config-map for easier/documented update depending upon the k8s install you might have?

For anyone who might find this issue and needs help here is what I ended up needing to do in order to get this to work with kops

updates to server.yaml
```
diff --git a/deploy/server.yaml b/deploy/server.yaml
index 9cd82ad..6d08710 100644
--- a/deploy/server.yaml
+++ b/deploy/server.yaml
@@ -17,10 +17,14 @@ spec:
       serviceAccountName: kiam-server
       nodeSelector:
         kubernetes.io/role: master
+      tolerations:
+      - key: "node-role.kubernetes.io/master"
+        effect: "NoSchedule"
+        operator: "Exists"
       volumes:
         - name: ssl-certs
           hostPath:
-            path: /usr/share/ca-certificates
+            path: /etc/ssl/certs
         - name: tls
           secret:
             secretName: kiam-server-tls
```
trust-policy.json
```json
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
          "Service": "ec2.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
      },
      {
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
          "AWS": "arn:aws:iam::{{Account ID}}:role/masters.k8s.clusterdomain.com"
        },
        "Action": "sts:AssumeRole"
      }
    ]
  }
```

**Comment by pingles** [comment] 2018-02-16 14:59
> Maybe include ca-certificates in the docker image to avoid different underlying hosts having ca-certificates in the wrong places or create config-map for easier/documented update depending upon the k8s install you might have?

I'd rather continue to mount from the host. I know this is somewhat host/cluster specific but it means that updates can be processed as the nodes are upgraded, rather than relying on each container having to

**Comment by pingles** [comment] 2018-02-16 15:08
Remember that the `/etc/ssl/certs` is the location that the Go HTTP client is using to check for certificates to ensure it can talk to AWS and isn't related to the agent accessing the server.

**Comment by luispollo** [comment] 2018-05-04 00:40
@cdenneen Your comments and patches saved the day for me. Thank you very much!

**Comment by josselin-c** [comment] 2018-10-10 08:49
For the record, on a Kubernetes 1.11 created via Kops, I had to use `/usr/share/ca-certificates/mozilla` instead of `/usr/share/ca-certificates`

**Comment by edgar-humberto** [comment] 2018-11-13 07:38
I am getting that error as well.

`error warming credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided`

Here is the full error. 
```
{"generation.metadata":0,"level":"error","msg":"error warming credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided","pod.iam.role":"kiam_sample","pod.name":"nodeapp-54b89ff69d-zk65q","pod.namespace":"iam-example","pod.status.ip":"","pod.status.phase":"Pending","resource.version":"2695","time":"2018-11-13T07:09:33Z"}
```
However when I `exec` into the pod `kubectl exec -it -n kube-system kiam-server-88f4j -- /bin/sh`

 I could see the certificate being mounted and the contents of the files were as expected. 

<img width="1007" alt="screenshot 2018-11-12 23 26 15" src="https://user-images.githubusercontent.com/1854719/48397396-5ea21000-e6d2-11e8-925d-c907abead2c8.png">

This was odd because on the host I could not find the certificates for the life of me in either 
- /etc/ssl/certs
- /usr/share/ca-certificates

Clearly I am missing something here, can someone help me understand what I am doing wrong ?

**Comment by pingles** [comment] 2018-11-13 08:56
@edgar-humberto it'll depend on your host distribution- what are you using?

**Comment by edgar-humberto** [comment] 2018-11-13 16:39
@pingles I am using Kops and the OS is Debian Jessie. Also I noticed that it is recommended that the server and the agent b on different nodes and use the nodeSelector attribute , I totally get that, but for the time being I have the server and the agent on the same nodes. I dont think this would be a problem but mentioning it just in case.

**Comment by edgar-humberto** [comment] 2018-11-14 09:35
Am I correct in thinking that I need to have the server and the agent on different hosts?

**Comment by Joseph-Irving** [comment] 2018-11-14 09:39
@edgar-humberto Yes that the agents and server have to be on different hosts.

This is because the agent writes iptables rules so that any aws metadata call on a host goes via the agent process which talks to the kiam server. 
So if you have the agent on the same host as the server, when the server tries to get AWS creds it will go via the agent and get forwarded to a kiam server, so you'll get a cyclic dependency and never get any creds for the server to work.

**Comment by edgar-humberto** [comment] 2018-11-14 09:54
@Joseph-Irving thanks for the reply. I will create a new instance group in Kops. I hope this solves my issue.

**Comment by edgar-humberto** [comment] 2018-11-14 22:43
Yup, that fixed it for me.  Ran the server and agent on different instance groups, also I had to change my interface configuration to crb0 for the agent.

```
          args:
            - agent
            - --iptables
            - --host-interface=cbr0
```
The default interface in the example is `cali+`, which prevented my pods from actually communicating with the kiam-agent.


Thank you for the help and for kiam, saved me a ton of work.

**Comment by edgar-humberto** [comment] 2018-11-16 07:36
OK, so I have this same issue popping up again when I switch my kops topology to private and set the networking interface to weave. 

Is there something more that I need to do in order to get kiam to work with weave other than set the `- --host-interface=weave`? 

Am I missing some other setting?
