### ISSUE TITLE
kiam server HA. Context deadline exceeded while rotating servers.

### ISSUE THREAD

**Issue by max-lobur** [uswitch/kiam#217] opened 2019-02-18 16:59 UTC
In my test AWS lab I run 3 masters with KIAM servers (`quay.io/uswitch/kiam:v3.0`) and 6 nodes with KIAM agents (same images). I'm getting these 
```
{"addr":"100.112.154.80:56850","level":"error","method":"GET","msg":"error processing request: rpc error: code = DeadlineExceeded desc = context deadline exceeded","path":"/latest/meta-data/iam/security-credentials/","status":500,"time":"2019-02-18T16:48:17Z"}
```
every time I'm rotating masters. The error starts to appear on every one of 6 agents, once I remove at least 1 master. To stop it I need to restart all agents, when they restart they start to work normally. This does not happen if I rotate kiam server itself (delete the pod), only when I rotate the whole master instance.

I'm using this chart https://github.com/helm/charts/tree/master/stable/kiam to run kiam. No special tuning, except for I'm setting `gatewayTimeoutCreation: 500ms` on both agent and server. 

Am I missing smth important in docs, some flag? Please suggest

**Comment by complex64** [comment] 2019-04-23 15:20
Same issue here, KIAM v.3.2

**Comment by MilanDasek** [comment] 2019-07-17 09:14
similar issue, kiam v3.3

**Comment by mehstg** [comment] 2019-07-17 15:35
Just been burned by this myself

**Comment by mseiwald** [comment] 2019-07-24 11:06
Same issue for us on kiam v3.0

**Comment by Joseph-Irving** [comment] 2019-07-30 08:35
We run Kiam in relatively large clusters and we regularly terminate our master nodes (we don't allow them to live longer than 7 days) and we've never seen this behaviour.

Kiam should be using a service with `clusterIP: none` this is so that the agents can use grpc loadbalancing, they go and discover the pod ips of each kiam-server and will loadbalance between them, if one goes down it will just try another. So I'm very puzzled as to how you're seeing this. 

I'd be interested to know what networking stack you're using, incase there's some commonality there which could be what's causing this behaviour.

**Comment by mehstg** [comment] 2019-07-30 09:02
We are using the amazon-k8s-cni plugin for networking. No other service mesh/network policy currently.

**Comment by denispesikov** [comment] 2019-07-30 16:00
Same here 
`error processing request: error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded`
KIAM v3.2
Any workaround?

**Comment by max-lobur** [comment] 2019-07-30 17:18
Using calico over aws ec2. 
Also using this chart to deploy https://github.com/helm/charts/tree/master/stable/kiam
It seems that it uses proper service as you mentioned https://github.com/helm/charts/blob/master/stable/kiam/templates/server-service.yaml#L26

**Comment by rhysemmas** [comment] 2019-08-16 08:38
I am struggling to reproduce the issue myself - when killing Kiam servers in various different ways, the Kiam agent is correctly load balancing between the remaining Kiam servers.

In order to observe the agent's behaviour, I set the following env vars in the agent pod to increase the log verbosity of grpc:

`GRPC_GO_LOG_SEVERITY_LEVEL=info`
`GRPC_GO_LOG_VERBOSITY_LEVEL=8`

The following events occur on 1 agent that load balances between 2 different servers:

The agent starts up and performs some service discovery to find the servers:

```
INFO: 2019/08/15 14:01:25 parsed scheme: "dns"
INFO: 2019/08/15 14:01:25 ccResolverWrapper: got new service config:
INFO: 2019/08/15 14:01:25 ccResolverWrapper: sending new addresses to cc: [{10.244.2.2:443 1 10-244-2-2.kiam-server.kube-system.svc.cluster.local. <nil>} {10.244.1.3:443 1 10-244-1-3.kiam-server.kube-system.svc.cluster.local. <nil>} {10.244.1.3:443 0  <nil>} {10.244.2.2:443 0  <nil>}]
```

The agent connects to the servers successfully (below) - note that each server is associated with a hex value, in this instance we have the following 2 servers:
10.244.1.3 - 0xc4203c1d40
10.244.2.2 - 0xc4203c1d60

```
INFO: 2019/08/15 14:01:25 base.baseBalancer: got new ClientConn state:  {{[{10.244.1.3:443 0  <nil>} {10.244.2.2:443 0  <nil>}] <nil>} <nil>}
INFO: 2019/08/15 14:01:25 base.baseBalancer: handle SubConn state change: 0xc4203c1d40, CONNECTING
INFO: 2019/08/15 14:01:25 base.baseBalancer: handle SubConn state change: 0xc4203c1d60, CONNECTING
INFO: 2019/08/15 14:01:25 base.baseBalancer: handle SubConn state change: 0xc4203c1d60, READY
INFO: 2019/08/15 14:01:25 roundrobinPicker: newPicker called with readySCs: map[{10.244.2.2:443 0  <nil>}:0xc4203c1d60]
```

^ here, one of the grpc connections becomes ready before the other and the 'roundrobinPicker' lists this as the only server available in its pool to load balance with.

```
INFO: 2019/08/15 14:01:25 base.baseBalancer: handle SubConn state change: 0xc4203c1d40, READY
INFO: 2019/08/15 14:01:25 roundrobinPicker: newPicker called with readySCs: map[{10.244.1.3:443 0  <nil>}:0xc4203c1d40 {10.244.2.2:443 0  <nil>}:0xc4203c1d60]
```

^ the other connection becomes ready and the load balancing pool is updated to include the second server.

At this point, I kill one of the Kiam servers (10.244.1.3 - 0xc4203c1d40):

```
INFO: 2019/08/15 14:15:32 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2019/08/15 14:15:32 base.baseBalancer: handle SubConn state change: 0xc4203c1d40, CONNECTING
WARNING: 2019/08/15 14:15:32 grpc: addrConn.createTransport failed to connect to {10.244.1.3:443 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.244.1.3:443: connect: connection refused". Reconnecting...`
```

^ the agent attempts to reconnect to the server I killed. The agent will continue to try and re-connect with the server that has gone away over time (I have omitted these logs)

```
INFO: 2019/08/15 14:15:32 roundrobinPicker: newPicker called with readySCs: map[{10.244.2.2:443 0  <nil>}:0xc4203c1d60]
```

^ immediately after the connection error, the pool of servers to load balance with is updated to just include the 1 remaining server.

Throughout this, my curls from another pod to the meta-data API have been successful - there hasn't been any sign of the issue reported (these curls will also show in the agent logs but have been omitted above for clarity).

Would somebody be able to set the grpc log level env vars mentioned above in their agent deployments and provide agent logs? Including examples of agent startup and when a server is killed, so we can compare. Thanks.

**Comment by mehstg** [comment] 2019-08-16 13:17
Hi. I have collected logs as requested. 

Kiam Agent startup logs:
`{"level":"info","msg":"configuring iptables","time":"2019-08-16T12:47:59Z"}
{"level":"info","msg":"started prometheus metric listener 0.0.0.0:9620","time":"2019-08-16T12:47:59Z"}
INFO: 2019/08/16 12:47:59 parsed scheme: "dns"
INFO: 2019/08/16 12:47:59 ccResolverWrapper: got new service config: 
INFO: 2019/08/16 12:47:59 ccResolverWrapper: sending new addresses to cc: [{10.2.81.71:443 1 10-2-81-71.kiam-server.iam-proxy.svc.cluster.local. <nil>} {10.2.118.49:443 1 10-2-118-49.kiam-server.iam-proxy.svc.cluster.local. <nil>} {10.2.118.49:443 0  <nil>} {10.2.81.71:443 0  <nil>}]
INFO: 2019/08/16 12:47:59 base.baseBalancer: got new resolved addresses:  [{10.2.81.71:443 1 10-2-81-71.kiam-server.iam-proxy.svc.cluster.local. <nil>} {10.2.118.49:443 1 10-2-118-49.kiam-server.iam-proxy.svc.cluster.local. <nil>} {10.2.118.49:443 0  <nil>} {10.2.81.71:443 0  <nil>}]
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc4201891a0, CONNECTING
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc4201891c0, CONNECTING
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc4201891e0, CONNECTING
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc420189210, CONNECTING
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc4201891c0, READY
INFO: 2019/08/16 12:47:59 roundrobinPicker: newPicker called with readySCs: map[{10.2.118.49:443 1 10-2-118-49.kiam-server.iam-proxy.svc.cluster.local. <nil>}:0xc4201891c0]
{"level":"info","msg":"listening :8181","time":"2019-08-16T12:47:59Z"}
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc4201891e0, READY
INFO: 2019/08/16 12:47:59 roundrobinPicker: newPicker called with readySCs: map[{10.2.118.49:443 1 10-2-118-49.kiam-server.iam-proxy.svc.cluster.local. <nil>}:0xc4201891c0 {10.2.118.49:443 0  <nil>}:0xc4201891e0]
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc420189210, READY
INFO: 2019/08/16 12:47:59 roundrobinPicker: newPicker called with readySCs: map[{10.2.118.49:443 1 10-2-118-49.kiam-server.iam-proxy.svc.cluster.local. <nil>}:0xc4201891c0 {10.2.118.49:443 0  <nil>}:0xc4201891e0 {10.2.81.71:443 0  <nil>}:0xc420189210]
INFO: 2019/08/16 12:47:59 base.baseBalancer: handle SubConn state change: 0xc4201891a0, READY
INFO: 2019/08/16 12:47:59 roundrobinPicker: newPicker called with readySCs: map[{10.2.81.71:443 1 10-2-81-71.kiam-server.iam-proxy.svc.cluster.local. <nil>}:0xc4201891a0 {10.2.118.49:443 1 10-2-118-49.kiam-server.iam-proxy.svc.cluster.local. <nil>}:0xc4201891c0 {10.2.118.49:443 0  <nil>}:0xc4201891e0 {10.2.81.71:443 0  <nil>}:0xc420189210]
{"addr":"10.2.45.198:41134","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:03Z"}
{"addr":"10.2.45.198:41172","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:06Z"}
{"addr":"10.2.45.198:41188","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:09Z"}
{"addr":"10.2.45.198:41198","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:12Z"}
{"addr":"10.2.45.198:41240","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:15Z"}
{"addr":"10.2.45.198:41264","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:18Z"}
{"addr":"10.2.45.198:41276","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:21Z"}
{"addr":"10.2.45.198:41310","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:24Z"}
{"addr":"10.2.45.198:41336","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:27Z"}
{"addr":"10.2.45.198:41348","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:48:30Z"}`
We have two KIAM servers running, 
`
1 10-2-81-71.kiam-server.iam-proxy.svc.cluster.local
10-2-118-49.kiam-server.iam-proxy.svc.cluster.local
`
If I run a curl from one of my containers, it works successfully:
`root@channel-service-588c949b66-tvxrr:/opt/app# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service
{"Code":"Success","Type":"AWS-HMAC","AccessKeyId":"redacted","SecretAccessKey":"redacted","Token":"redacted","Expiration":"2019-08-16T13:19:47Z","LastUpdated":"2019-08-16T13:04:47Z"}`

I then kill the EC2 host running one of the KIAM servers (10-2-118-49.kiam-server.iam-proxy.svc.cluster.local), these are specific worker nodes that only run the KIAM servers.
Almost immediately the curl begins to fail:
`root@channel-service-588c949b66-tvxrr:/opt/app# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service
error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded`

The KIAM agent logs during this period are as follows:
`{"addr":"10.2.39.230:52366","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:50:52Z"}
{"addr":"10.2.39.230:52366","duration":5000,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:50:52Z"}
{"addr":"10.2.45.198:42582","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:50:54Z"}
{"addr":"10.2.39.230:52422","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = Canceled desc = context canceled","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:50:56Z"}
{"addr":"10.2.39.230:52422","duration":2407,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:50:56Z"}
{"addr":"10.2.45.198:42612","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:50:57Z"}
{"addr":"10.2.45.198:42620","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:00Z"}
{"addr":"10.2.39.230:52466","duration":2,"headers":{"Content-Type":["application/json"]},"level":"debug","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":200,"time":"2019-08-16T12:51:01Z"}
{"addr":"10.2.45.198:42650","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:03Z"}
{"addr":"10.2.39.230:52488","duration":1,"headers":{"Content-Type":["application/json"]},"level":"debug","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":200,"time":"2019-08-16T12:51:03Z"}
{"addr":"10.2.45.198:42688","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:06Z"}
{"addr":"10.2.39.230:52504","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:51:09Z"}
{"addr":"10.2.39.230:52504","duration":5000,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:51:09Z"}
{"addr":"10.2.45.198:42700","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:09Z"}
{"addr":"10.2.45.198:42710","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:12Z"}
{"addr":"10.2.45.198:42748","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:15Z"}
{"addr":"10.2.45.198:42772","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:18Z"}
{"addr":"10.2.45.198:42790","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:21Z"}
{"addr":"10.2.39.230:52602","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:51:21Z"}
{"addr":"10.2.39.230:52602","duration":5000,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-16T12:51:21Z"}
{"addr":"10.2.45.198:42824","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:24Z"}
{"addr":"10.2.45.198:42850","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:27Z"}
{"addr":"10.2.45.198:42858","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-16T12:51:30Z"}
`

**Comment by rhysemmas** [comment] 2019-08-16 13:45
Hi @mehstg - thanks for providing those logs. It is strange that you aren't seeing any gRPC logs (the `INFO` and `WARNING` events) in the agent logs after killing the kiam server - are there definitely none of these entries in the agent logs when the cURLs begin to fail?

**Comment by mehstg** [comment] 2019-08-16 13:59
No unfortunately not. I just tested again and I only really see the info messages during startup.

**Comment by rhysemmas** [comment] 2019-08-16 14:27
OK - thanks for double checking. A few questions:

The IP addresses that are resolved in your logs above, are these the same as your kiam server pod IPs? 
Could you confirm what your cpu and memory resource requests/limits are for the agent pods?
Are you also using the helm chart to deploy kiam?

Also, could you please try running kiam v3.4 (released today), as this includes some gRPC updates, and let us know if this changes any behaviour.

**Comment by mehstg** [comment] 2019-08-16 14:55
I actually am not setting any resources on the pods. Deploying from the stable helm charts (v2.2.0).
IP addresses resolved are correct.
Will try upgrading to v3.4 on one of the test clusters on Monday and test again

**Comment by rhysemmas** [comment] 2019-08-16 15:15
I'd recommend setting some resource requests, at least for the agent pods so they are not starved of resources. We use the following values for the agents which works fine (but will depend on the scale of your cluster)

```
resources:
            requests:
              cpu: 5m
              memory: 50Mi
            limits:
              memory: 100Mi
```

and the server resources are set to the following:
```
resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              memory: 512Mi
```

**Comment by mehstg** [comment] 2019-08-19 12:59
I have set resource requests on my KIAM pods and also upgraded to KIAM v3.4 on one of my test cluster.
Running the same test, I am seeing the same issues, however it seems to be alternate requests fail now after killing one of my KIAM servers (This cluster has two KIAM servers running).

Previously, every request would die after killing one of the KIAM servers, so I wonder if the load balancing is working better in v3.4 but the dead server is still being cached somewhere. Log attached

`{"addr":"10.2.67.14:59876","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-19T12:54:33Z"}
{"addr":"10.2.71.87:54470","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-19T12:54:33Z"}
{"addr":"10.2.71.87:54470","duration":5000,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-19T12:54:33Z"}
{"addr":"10.2.71.87:54516","duration":1,"headers":{"Content-Type":["application/json"]},"level":"debug","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":200,"time":"2019-08-19T12:54:35Z"}
{"addr":"10.2.67.14:59892","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-19T12:54:36Z"}
{"addr":"10.2.67.14:59914","duration":0,"headers":{},"level":"debug","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2019-08-19T12:54:39Z"}
{"addr":"10.2.71.87:54524","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = Canceled desc = context canceled","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-19T12:54:39Z"}
{"addr":"10.2.71.87:54524","duration":2004,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/stage-eu-west-1-stage01-pod-connectt-api-channel-service","status":500,"time":"2019-08-19T12:54:39Z"}`

**Comment by daviddyball** [comment] 2019-09-11 20:37
I have been bitten by this as well. I haven't had a chance to enable gRPC logs to provide, but I am wondering if this has to do with `kiam-server` running as a `DaemonSet` and not receiving proper signals when a master terminates (e.g. when running a `kops rolling-update cluster` on masters).

My knowledge of gRPC is lacking, but perhaps when you manually terminate a `kiam-server` pod by running `kubectl delete pod kiam-server-xxxxxx` it sends some kind of message to the gRPC client in `kiam-agent`?

I'll try and get some time to do further testing on my end and let you know how I go anyway. 

As a side-note I have a PR open to convert the `DaemonSet` for `kiam-server` to a `Deployment` so that it handles termination more gracefully. Perhaps the two are linked?

**Comment by rhysemmas** [comment] 2019-09-24 15:43
Hi @daviddyball, thanks for adding your findings. I have been trying to replicate the issue and I am still struggling - killing the Kiam server in various ways (deleting pod, forcefully deleting pod, terminating node, rebooting node) whilst sending requests to a Kiam agent has not reproduced the `context deadline exceeded` error for me that is being reported.

From looking at the logs you've provided when Kiam server is running as a daemonset, the gRPC client on the agent does seem to be behaving normally when a server goes away; it notices the gRPC server connection failing as the master nodes are recycled:

```
INFO: 2019/09/12 10:12:33 base.baseBalancer: handle SubConn state change: 0xc4201779f0, TRANSIENT_FAILURE
```

^ The connection to a server enters failure state

```
INFO: 2019/09/12 10:12:33 roundrobinPicker: newPicker called with readySCs: map[{100.96.12.99:443 1 100-96-12-99.kiam-server.kube-system.svc.cluster.local. <nil>}:0xc4203d4db0 {100.96.9.121:443 0  <nil>}:0xc4203d5b10 {100.96.12.99:443 0  <nil>}:0xc4203d4e80 {100.96.11.93:443 1 100-96-11-93.kiam-server.kube-system.svc.cluster.local. <nil>}:0xc420177a10 {100.96.10.125:443 1 100-96-10-125.kiam-server.kube-system.svc.cluster.local. <nil>}:0xc420177a30 {100.96.11.93:443 0  <nil>}:0xc420177ac0 {100.96.10.125:443 0  <nil>}:0xc420177aa0]
```

^ The loadbalancing pool updates immediately to drop the failing server (the `0xc4201779f0` value does not appear in the list)

This occurs with another Kiam server at the same time `10:12:33`:
```
INFO: 2019/09/12 10:12:33 base.baseBalancer: handle SubConn state change: 0xc4203d5b10, TRANSIENT_FAILURE
INFO: 2019/09/12 10:12:33 roundrobinPicker: newPicker called with readySCs: map[{100.96.12.99:443 1 100-96-12-99.kiam-server.kube-system.svc.cluster.local. <nil>}:0xc4203d4db0 {100.96.12.99:443 0  <nil>}:0xc4203d4e80 {100.96.10.125:443 0  <nil>}:0xc420177aa0 {100.96.10.125:443 1 100-96-10-125.kiam-server.kube-system.svc.cluster.local. <nil>}:0xc420177a30 {100.96.11.93:443 0  <nil>}:0xc420177ac0 {100.96.11.93:443 1 100-96-11-93.kiam-server.kube-system.svc.cluster.local. <nil>}:0xc420177a10]
```

So I am not entirely sure what is causing the issue yet. I am still trying to replicate this issue, though, and if you are happy to share it would be useful to me if you could confirm the following:

How are you deploying Kiam to your cluster (e.g, Helm/manifest files)?
Which version of Kiam are you running?
What DNS service are you running in your cluster (e.g, kube-dns, coreDNS)?

**Comment by daviddyball** [comment] 2019-09-24 16:45
Hey @rhysemmas,

Here's my setup:

#### How are you deploying Kiam to your cluster (e.g, Helm/manifest files)?
Flat YAML manifests

#### Which version of Kiam are you running?
`quay.io/uswitch/kiam:v3.3`

#### What DNS service are you running in your cluster (e.g, kube-dns, coreDNS)?
CoreDNS: `k8s.gcr.io/coredns:1.1.3`

**Comment by mehstg** [comment] 2019-09-24 18:59
Out of interest David. What CNI are you using? I am using the
amazon-vpc-cni. Wondering if there is another similarity in our
configurations that we are missing.

**Comment by rgardam** [comment] 2019-09-25 05:43
I'm seeing this on a kops update and rolling of the cluster.

I'm seeing kops try to drain the nodes, but fails to take any notice of daemon-sets. 
` WARNING: Ignoring DaemonSet-managed pods:` 

Kops then terminates the node via the aws autoscaling group api.

We are using
calico cni
k8s v1.13.10
quay.io/uswitch/kiam:v3.3

**Comment by daviddyball** [comment] 2019-09-25 09:21
@mehstg I'm using Calcio CNI

**Comment by mehstg** [comment] 2019-09-25 12:40
Ha. Ok, so all on different CNI's

**Comment by wskulley** [comment] 2019-10-31 17:57
Saw this (again) today on a rolling update of 1.13 masters (kops)

quay.io/uswitch/kiam:v3.3
helm kiam-2.5.1
canal CNI
CoreDNS

**Comment by daviddyball** [comment] 2019-11-01 09:45
I should report that since moving `kiam-server` to a `Deployment` instead of a `DaemonSet` we've not experienced any issues on our 6 clusters, including a migration from 1.11 -> 1.12 -> 1.13 -> 1.14 for all of them. I think this is down to each server component being gracefully terminated when the `Deployment` drains correctly due to `kubectl drain` correctly handling the `Deployment` and sending proper `SIGTERM` events to pods.

While this doesn't solve the issue of random server failures causing the same issue, it does mean we can roll our control plane without fear of breaking our workloads IAM credentials.

**Comment by jacksontj** [comment] 2019-11-01 15:48
If you need to evict a DS before a node dies you can actually do so by applying a `NoExecute` taint like so:


```
kubectl taint nodes node1 key=value:NoExecute
```

This will remove any/all pods from the node -- this should be done after a drain (as usually the running non-ds pods have deps on the ds pods). If you (for some reason) still need a ds instead of a deployment.

**Comment by daviddyball** [comment] 2019-11-01 15:49
Nice to know @jacksontj. We're using `kops` to roll our nodes and there's currently no option that I know of to apply an additional taint to a node before it gets killed. It does seem like a good way to get around this issue too while still using a `Deployment`.

**Comment by mehstg** [comment] 2019-11-06 16:39
Ok. So I have just been burned by this again on our prod system. Cert-manager replaced the TLS certificates used by KIAM and the kiam-servers rebooted.
This caused all of the kiam-agents to immediately start logging `error processing request: rpc error: code = DeadlineExceeded desc = context deadline exceeded` and we lost all pod IAM access.

**Comment by mechpen** [comment] 2019-11-22 22:58
My root cause theory is based on the following facts:

1. for calico cni, when a node is deleted, all packets from the node is dropped.
2. when kiam-server is deployed as a daemonset, rolling nodes does not kill the kiam-server pods before deleting the nodes.
3. this gRPC issue: https://github.com/grpc/grpc-go/issues/3206

**Comment by mehstg** [comment] 2019-11-24 13:18
@mechpen - Great spot. I have been doing some testing today and inserted the Keepalive in to a local branch of Kiam - https://github.com/mehstg/kiam/tree/grpc-keepalive-testing

I have just spun it up on one of my test clusters, and cannot get it to fail now, whether I ungracefully terminate the instance, or drain it correctly.

**Comment by Joseph-Irving** [comment] 2020-01-21 13:35
Kiam v3.5 https://github.com/uswitch/kiam/releases/tag/v3.5 has a potential fix for this issue, has anyone been able to reproduce it on 3.5?

**Comment by nirnanaaa** [comment] 2020-01-21 13:37
how should cli arguments be tuned to fix this issue from happening @Joseph-Irving ?

**Comment by mechpen** [comment] 2020-01-21 21:44
@nirnanaaa the default values should be good.

**Comment by mbelang** [comment] 2020-03-06 16:28
I'm at 3.5 with both server and agent as daemonset and I have the problem.

**Comment by jkassis** [comment] 2020-07-29 02:56
i'm seeing this now in KIAM v3.5 with OpenShift 4.5 in AWS. Comes right up when i install the helm chart. can't get the kiam-server stable.

**Comment by jkassis** [comment] 2020-07-29 03:41
in my case... the server was continuously and consistently failing the first liveness / readiness probes. it was 100% due to running the health check against 127.0.0.1 rather than localhost... here are my current working okd4.5 overrides for v3.5 chart...

`server:
  assumeRoleArn: "arn:aws:iam::807125168235:role/k8s-kiam-server"
  useHostNetwork: true
  log:
    level: debug
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  sslCertHostPath: /etc/ssl/certs
  probes:
    serverAddress: localhost
agent:
  host:
    iptables: true
  log:
    level: debug
  extraHostPathMounts:
    - name: ssl-certs
      mountPath: /etc/ssl/certs
      hostPath: /etc/ssl/certs
      readOnly: true
  nodeSelector:
    node-role.kubernetes.io/worker: ""`

**Comment by shrutilamba** [comment] 2020-08-19 09:32
I am still getting the same error even after upgrading to v3.5. Whenever a new node comes up, the agent restarts with the following error:
`"msg":"error creating server gateway: error dialing grpc server: context deadline exceeded"`
Anyone else also facing this issue?

**Comment by vtremblay** [comment] 2020-10-14 01:44
I have the same issue. I'm running v3.2, installed with the helm chart v2.3.0. I am not sure what triggers the issuebetween the rotation of the certificates generated by cert-manager or a rotation of kiam-server itself.

When the issue is occurring, changing the --server-address=kiam-server:443 to --server-address=localhost:443 in the agent's daemonset seems to fix it.

**Comment by pingles** [comment] 2020-11-11 18:31
I linked to #425 but it's potentially related to the way the gRPC load-balancer manages connection failures. We've updated the version of gRPC and it (according to the gRPC team) can be managed through controlling the MaxConnectionAge setting.

We'll hopefully get this into v4 so this issue ought to be resolvable through that.

**Comment by pingles** [comment] 2020-12-16 10:39
We've updated gRPC and the changes in #433 should make it possible to mitigate the situation, according to the advice from the gRPC team: controlling the connection age to be shorter forces clients to re-poll for servers frequently.

I'm going to close this issue for now and people should follow that advice to manage. If we see other problems we can re-open.

Thanks for everyone in contributing and helping us to close this down. It was also reported in #425.

**Closed by pingles** 2020-12-16 10:39 UTC
